---
- name: "create ansible-image and build web-container"
  hosts: localhost
  tasks:      
    - name: stop current running container
      command: docker stop web-container
      ignore_errors: yes

    - name: remove stopped container
      command: docker rm web-container
      ignore_errors: yes

    - name: 'delete any image with same name'
      command: docker rmi engabdullah1909/web-app
      ignore_errors: yes

    - name: 'build the ansible-image'
      command: docker build -t engabdullah1909/web-app .

    - name: 'run web-container'
      command: docker run -d --name web-container -p 5000:80 engabdullah1909/web-app

    - name: 'push the image to docker rejestiry'
      command: docker push engabdullah1909/web-app

